name: Release Workflow

on:
  release:
    types: [released]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout A with submodules
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Install Dependencies (example-repo-A)
        run: yarn install

      - name: Clone Docs Repo
        run: git clone https://Mf-3d@github.com/Mf-3d/example-repo-B.git

      - name: Install Dependencies and Build Docs (example-repo-B)
        working-directory: ./example-repo-B
        run: |
          yarn install
          yarn build

      - name: Copy build files to /docs
        run: |
          if [ -d "./docs" ]; then rm -rf ./docs; fi
          mkdir ./docs
          cp -R ./example-repo-B/build/* ./docs
        
      - name: Cleanup
        run: rm -rf ./example-repo-B

      - name: Set git config
        run: |
          git config --local user.email "mf7cli120@icloud.com"
          git config --local user.name "Mf-3d"

      - name: Commit and push docs changes
        run: |
          git add .
          git commit  --allow-empty -m "📝 update docs for release ${{ github.event.release.tag_name }}!" -a
          git push origin HEAD:main