name: Release Workflow

on:
  release:
    types: [released]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout A with submodules
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Clone Docs Repo
        run: git clone https://Mf-3d@github.com/Mf-3d/example-repo-B.git

      - name: Install Dependencies and Build Docs
        working-directory: ./example-repo-B
        run: |
          yarn install
          yarn build

      - name: Copy build files to /docs
        run: cp -R ./example-repo-B/build ./docs
        
      - name: Cleanup
        run: rm -rf ./example-repo-B

      - name: Commit and push docs changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '📝 update docs for release ${{ github.event.release.tag_name }}!'
          commit_options: '--author="GitHub Actions <actions@github.com>"'
          branch: 'main'
          add_options: '-A'
          push_options: 'HEAD:main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
