
name: Release Workflow

on:
  release:
    types: [released]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Clone Docs Repo
        run: git clone https://Mf-3d@github.com/Mf-3d/example-repo-B.git
      - name: Install Dependencies and Build Docs
        working-directory: ./example-repo-B
        run: |
          yarn install
          yarn build
      - name: Commit and push docs changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit-message: "docs: update docs for release ${{ github.event.release.tag_name }}"
          commit-user-name: "GitHub Actions"
          commit-user-email: "actions@github.com"
          commit-branch: "main"
          commit-allow-empty: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}